name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: docker build -t murillocwb/sisfinan:latest .

      - name: Push para o Docker Hub
        run: docker push murillocwb/sisfinan:latest

      - name: Build da imagem Docker
        run: docker build -t murillosanti/sisfinan:latest .

      - name: Push da imagem para o Docker Hub
        run: docker push murillosanti/sisfinan:latest
